const collegeData = [
  { label: "Other", value: -1 },
  { label: "Indian Institute of Technology Kharagpur", value: 1 },
  { label: "Abhilashi University", value: 2 },
  { label: "Acharya N.G. Ranga Agricultural University", value: 3 },
  { label: "Acharya Nagarjuna University", value: 4 },
  { label: "Adamas University", value: 5 },
  { label: "Adesh University", value: 6 },
  { label: "Adikavi Nannaya University", value: 7 },
  { label: "Ahmedabad University", value: 8 },
  { label: "Ajeenkya D.Y. Patil University", value: 9 },
  { label: "Akal University", value: 10 },
  { label: "AKS University", value: 11 },
  { label: "Alagappa University", value: 12 },
  { label: "Alakh Prakash Goyal Shimla University", value: 13 },
  { label: "Al-Falah University", value: 14 },
  { label: "Aliah University", value: 15 },
  { label: "Aligarh Muslim University", value: 16 },
  { label: "All India Institute of Medical Sciences Bhopal", value: 17 },
  { label: "All India Institute of Medical Sciences Bhubaneswar", value: 18 },
  { label: "All India Institute of Medical Sciences Delhi", value: 19 },
  { label: "All India Institute of Medical Sciences Jodhpur", value: 20 },
  { label: "All India Institute of Medical Sciences Patna", value: 21 },
  { label: "All India Institute of Medical Sciences Raipur", value: 22 },
  { label: "All India Institute of Medical Sciences Rishikesh", value: 23 },
  { label: "Alliance University", value: 24 },
  { label: "Ambedkar University Delhi", value: 25 },
  { label: "Amity University", value: 26 },
  { label: "Amrita Vishwa Vidyapeetham", value: 27 },
  { label: "Anand Agricultural University", value: 28 },
  { label: "Anant National University", value: 29 },
  { label: "Andhra University", value: 30 },
  { label: "Anna University", value: 31 },
  { label: "Annamalai University", value: 32 },
  { label: "Apeejay Stya University", value: 33 },
  { label: "Apex Professional University", value: 34 },
  { label: "Apex University", value: 35 },
  { label: "APJ Abdul Kalam Technological University", value: 36 },
  { label: "Arka Jain University", value: 37 },
  { label: "Arni University", value: 38 },
  { label: "Arunachal University of Studies", value: 39 },
  { label: "Arunodaya University", value: 40 },
  { label: "Aryabhatta Knowledge University", value: 41 },
  { label: "Ashoka University", value: 42 },
  { label: "Assam Agricultural University", value: 43 },
  { label: "Assam Don Bosco University", value: 44 },
  { label: "Assam Down Town University", value: 45 },
  {
    label: "Assam Rajiv Gandhi University of Cooperative Management",
    value: 46,
  },
  { label: "Assam Science and Technology University", value: 47 },
  { label: "Assam University", value: 48 },
  { label: "Assam Women's University", value: 49 },
  { label: "Atal Bihari Vajpayee Hindi Vishwavidyalaya", value: 50 },
  { label: "Atal Bihari Vajpayee Vishwavidyalaya", value: 51 },
  { label: "Atmiya University", value: 52 },
  { label: "AURO University", value: 53 },
  { label: "Avantika University", value: 54 },
  { label: "Avinashilingam University", value: 55 },
  { label: "Awadhesh Pratap Singh University", value: 56 },
  { label: "Ayush and Health Sciences University of Chhattisgarh", value: 57 },
  { label: "Azim Premji University", value: 58 },
  {
    label: "B.S. Abdur Rahman Crescent Institute of Science and Technology",
    value: 59,
  },
  { label: "Baba Farid University of Health Sciences", value: 60 },
  { label: "Baba Ghulam Shah Badhshah University", value: 61 },
  { label: "Baba Mastnath University", value: 62 },
  { label: "Babasaheb Bhimrao Ambedkar Bihar University", value: 63 },
  { label: "Babasaheb Bhimrao Ambedkar University", value: 64 },
  { label: "Babu Banarasi Das University", value: 65 },
  {
    label: "Baddi University of Emerging Sciences and Technologies",
    value: 66,
  },
  { label: "BAHRA University", value: 67 },
  { label: "Banaras Hindu University", value: 68 },
  { label: "Banasthali Vidyapith", value: 69 },
  { label: "Banda University of Agriculture and Technology", value: 70 },
  { label: "Bangalore University", value: 71 },
  { label: "Bankura University", value: 72 },
  { label: "Bareilly International University", value: 73 },
  { label: "Barkatullah University", value: 74 },
  { label: "Bastar Vishwavidyalaya", value: 75 },
  { label: "Bengaluru North University", value: 76 },
  { label: "Bennett University", value: 77 },
  { label: "Berhampur University", value: 78 },
  { label: "Bhagat Phool Singh Mahila Vishwavidyalaya", value: 79 },
  { label: "Bhagwant University, Ajmer", value: 80 },
  { label: "Bhakta Kavi Narsinh Mehta University", value: 81 },
  { label: "Bharath Institute of Higher Education and Research", value: 82 },
  { label: "Bharathiar University", value: 83 },
  { label: "Bharathidasan University", value: 84 },
  { label: "Bharati Vidyapeeth Deemed University", value: 85 },
  { label: "Bhartiya Skill Development University", value: 86 },
  { label: "Bhatkhande Music Institute", value: 87 },
  { label: "Bhupal Nobles University", value: 88 },
  { label: "Bhupendra Narayan Mandal University", value: 89 },
  { label: "Bidhan Chandra Krishi Vishwavidyalaya", value: 90 },
  { label: "Bihar Agricultural University", value: 91 },
  { label: "Biju Patnaik University of Technology", value: 92 },
  { label: "Binod Bihari Mahto Koyalanchal University", value: 93 },
  { label: "Birla Institute of Technology", value: 94 },
  { label: "Birla Institute of Technology and Science", value: 95 },
  { label: "Birsa Agricultural University", value: 96 },
  { label: "BLDE University", value: 97 },
  { label: "BML Munjal University", value: 98 },
  { label: "Bodoland University", value: 99 },
  { label: "Brainware University", value: 100 },
  { label: "Bundelkhand University", value: 101 },
  { label: "C.U. Shah University", value: 102 },
  { label: "Career Point University", value: 103 },
  { label: "Central Agricultural University", value: 104 },
  { label: "Central Institute of Fisheries Education", value: 105 },
  { label: "Central Institute of Higher Tibetan Studies", value: 106 },
  { label: "Central University of Andhra Pradesh", value: 107 },
  { label: "Central University of Gujarat", value: 108 },
  { label: "Central University of Haryana", value: 109 },
  { label: "Central University of Himachal Pradesh", value: 110 },
  { label: "Central University of Jammu", value: 111 },
  { label: "Central University of Jharkhand", value: 112 },
  { label: "Central University of Karnataka", value: 113 },
  { label: "Central University of Kashmir", value: 114 },
  { label: "Central University of Kerala", value: 115 },
  { label: "Central University of Odisha", value: 116 },
  { label: "Central University of Punjab", value: 117 },
  { label: "Central University of Rajasthan", value: 118 },
  { label: "Central University of South Bihar", value: 119 },
  { label: "Central University of Tamil Nadu", value: 120 },
  {
    label: "Centurion University of Technology and Management, Odisha",
    value: 121,
  },
  { label: "CEPT University", value: 122 },
  { label: "Chanakya National Law University", value: 123 },
  { label: "Chandigarh University", value: 124 },
  {
    label: "Chandra Shekhar Azad University of Agriculture and Technology",
    value: 125,
  },
  { label: "Charotar University of Science and Technology", value: 126 },
  { label: "Chaudhary Bansi Lal University", value: 127 },
  {
    label: "Chaudhary Charan Singh Haryana Agricultural University",
    value: 128,
  },
  { label: "Chaudhary Charan Singh University", value: 129 },
  { label: "Chaudhary Devi Lal University", value: 130 },
  { label: "Chaudhary Ranbir Singh University", value: 131 },
  { label: "Chennai Mathematical Institute", value: 132 },
  { label: "Chhatrapati Shahu Ji Maharaj University", value: 133 },
  { label: "Chhattisgarh Kamdhenu Vishwavidyalaya", value: 134 },
  { label: "Chhattisgarh Swami Vivekananda Technical University", value: 135 },
  { label: "Children's University", value: 136 },
  { label: "Chitkara University, Himachal Pradesh", value: 137 },
  { label: "Chitkara University, Punjab", value: 138 },
  { label: "Christ University", value: 139 },
  { label: "Cluster University of Jammu", value: 140 },
  { label: "CMJ University", value: 141 },
  { label: "CMR University", value: 142 },
  { label: "Cochin University of Science and Technology", value: 143 },
  { label: "Cooch Behar Panchanan Barma University", value: 144 },
  { label: "Cotton University", value: 145 },
  { label: "CSK Himachal Pradesh Krishi Vishvavidyalaya", value: 146 },
  { label: "Dakshina Bharat Hindi Prachar Sabha", value: 147 },
  { label: "Damodaram Sanjivayya National Law University", value: 148 },
  { label: "Datta Meghe Institute of Medical Sciences", value: 149 },
  { label: "DAV University", value: 150 },
  { label: "Davangere University", value: 151 },
  { label: "Dayalbagh Educational Institute", value: 152 },
  { label: "Dayananda Sagar University", value: 153 },
  { label: "Deccan College Post-Graduate and Research Institute", value: 154 },
  { label: "Deen Dayal Upadhyay Gorakhpur University", value: 155 },
  {
    label: "Deenbandhu Chhotu Ram University of Science and Technology",
    value: 156,
  },
  {
    label: "Delhi Pharmaceutical Sciences and Research University",
    value: 157,
  },
  { label: "Delhi Technological University", value: 158 },
  { label: "Desh Bhagat University", value: 159 },
  { label: "Dev Sanskriti Vishwavidyalaya", value: 160 },
  { label: "Devi Ahilya Vishwavidyalaya", value: 161 },
  { label: "Dharmsinh Desai University", value: 162 },
  {
    label:
      "Dhirubhai Ambani Institute of Information and Communication Technology",
    value: 163,
  },
  { label: "Diamond Harbour Women's University", value: 164 },
  { label: "Dibrugarh University", value: 165 },
  { label: "DIT University", value: 166 },
  { label: "Doon University", value: 167 },
  { label: "Dr K.N. Modi University", value: 168 },
  { label: "Dr YSR Architecture and Fine Arts University", value: 169 },
  { label: "Dr. A.P.J Abdul Kalam University", value: 170 },
  { label: "Dr. A.P.J. Abdul Kalam Technical University", value: 171 },
  {
    label: "Dr. B R Ambedkar National Institute of Technology Jalandhar",
    value: 172,
  },
  { label: "Dr. B.R. Ambedkar University", value: 173 },
  { label: "Dr. B.R. Ambedkar University of Social Sciences", value: 174 },
  { label: "Dr. Babasaheb Ambedkar Marathwada University", value: 175 },
  { label: "Dr. Babasaheb Ambedkar Technological University", value: 176 },
  { label: "Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth", value: 177 },
  { label: "Dr. Bhimrao Ambedkar University", value: 178 },
  { label: "Dr. C.V. Raman University", value: 179 },
  { label: "Dr. D.Y. Patil Vidyapeeth", value: 180 },
  { label: "Dr. Hari Singh Gour University", value: 181 },
  { label: "Dr. M.G.R. Educational and Research Institute", value: 182 },
  { label: "Dr. N.T.R. University of Health Sciences", value: 183 },
  { label: "Dr. Panjabrao Deshmukh Krishi Vidyapeeth", value: 184 },
  { label: "Dr. Rajendra Prasad Central Agricultural University", value: 185 },
  { label: "Dr. Ram Manohar Lohia Avadh University", value: 186 },
  { label: "Dr. Ram Manohar Lohiya National Law University", value: 187 },
  {
    label: "Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University",
    value: 188,
  },
  {
    label: "Dr. Shakuntala Misra National Rehabilitation University",
    value: 189,
  },
  { label: "Dr. Vishwanath Karad MIT World Peace University", value: 190 },
  {
    label: "Dr. Y.S. Parmar University of Horticulture and Forestry",
    value: 191,
  },
  { label: "Dr. Y.S.R. Horticultural University", value: 192 },
  { label: "Dravidian University", value: 193 },
  { label: "EIILM University", value: 194 },
  { label: "Era University", value: 195 },
  { label: "Eternal University", value: 196 },
  { label: "Fakir Mohan University", value: 197 },
  { label: "Flame University", value: 198 },
  { label: "Forest Research Institute", value: 199 },
  { label: "G.H. Raisoni University", value: 200 },
  { label: "G.L.S. University", value: 201 },
  { label: "Galgotias University", value: 202 },
  { label: "Gandhi Institute of Technology and Management", value: 203 },
  { label: "Gandhigram Rural University", value: 204 },
  { label: "Gangadhar Meher University", value: 205 },
  { label: "Ganpat University", value: 206 },
  { label: "Garden City University", value: 207 },
  { label: "Gauhati University", value: 208 },
  { label: "Gautam Buddha University", value: 209 },
  { label: "GD Goenka University", value: 210 },
  { label: "Geetanjali University", value: 211 },
  { label: "GIET University", value: 212 },
  { label: "GLA University", value: 213 },
  { label: "Glocal University", value: 214 },
  { label: "GNA University", value: 215 },
  { label: "Goa University", value: 216 },
  { label: "Gokhale Institute of Politics and Economics", value: 217 },
  { label: "Gondwana University", value: 218 },
  {
    label: "Govind Ballabh Pant University of Agriculture and Technology",
    value: 219,
  },
  { label: "Govind Guru Tribal University", value: 220 },
  { label: "Graphic Era Hill University", value: 221 },
  { label: "Graphic Era University", value: 222 },
  { label: "GSFC University", value: 223 },
  { label: "Gujarat Ayurved University", value: 224 },
  { label: "Gujarat Forensic Sciences University", value: 225 },
  { label: "Gujarat National Law University", value: 226 },
  { label: "Gujarat Technological University", value: 227 },
  { label: "Gujarat University", value: 228 },
  { label: "Gujarat University of Transplantation Sciences", value: 229 },
  { label: "Gujarat Vidyapith", value: 230 },
  { label: "Gulbarga University", value: 231 },
  {
    label: "Guru Angad Dev Veterinary and Animal Sciences University",
    value: 232,
  },
  { label: "Guru Ghasidas Vishwavidyalaya", value: 233 },
  { label: "Guru Gobind Singh Indraprastha University", value: 234 },
  {
    label: "Guru Jambheshwar University of Science and Technology",
    value: 235,
  },
  { label: "Guru Kashi University", value: 236 },
  { label: "Guru Nanak Dev University", value: 237 },
  { label: "Guru Ravidas Ayurved University", value: 238 },
  { label: "Gurukul Kangri Vishwavidyalaya", value: 239 },
  { label: "Harcourt Butler Technical University", value: 240 },
  {
    label: "Haridev Joshi University of Journalism and Mass Communication",
    value: 241,
  },
  { label: "Hemchandracharya North Gujarat University", value: 242 },
  { label: "Hemwati Nandan Bahuguna Garhwal University", value: 243 },
  {
    label: "Hemwati Nandan Bahuguna Uttarakhand Medical Education University",
    value: 244,
  },
  { label: "Hidayatullah National Law University", value: 245 },
  { label: "Himachal Pradesh Technical University", value: 246 },
  { label: "Himachal Pradesh University", value: 247 },
  { label: "Himalayan Garhwal University", value: 248 },
  { label: "Himalayan University", value: 249 },
  { label: "Himgiri ZEE University", value: 250 },
  { label: "Hindustan Institute of Technology and Science", value: 251 },
  { label: "Homi Bhabha National Institute", value: 252 },
  { label: "ICFAI University, Dehradun", value: 253 },
  { label: "ICFAI University, Himachal Pradesh", value: 254 },
  { label: "ICFAI University, Jaipur", value: 255 },
  { label: "ICFAI University, Jharkhand", value: 256 },
  { label: "ICFAI University, Meghalaya", value: 257 },
  { label: "ICFAI University, Mizoram", value: 258 },
  { label: "ICFAI University, Nagaland", value: 259 },
  { label: "ICFAI University, Raipur", value: 260 },
  { label: "ICFAI University, Sikkim", value: 261 },
  { label: "ICFAI University, Tripura", value: 262 },
  { label: "IEC University", value: 263 },
  { label: "IFHE Hyderabad", value: 264 },
  { label: "IFTM University", value: 265 },
  { label: "IIHMR University", value: 266 },
  { label: "IIMT University", value: 267 },
  { label: "IMS Unison University", value: 268 },
  { label: "Indian Agricultural Research Institute", value: 269 },
  {
    label: "Indian Institute of Engineering Science and Technology, Shibpur",
    value: 270,
  },
  { label: "Indian Institute of Foreign Trade", value: 271 },
  { label: "Indian Institute of Information Technology Allahabad", value: 272 },
  {
    label: "Indian Institute of Information Technology and Management Gwalior",
    value: 273,
  },
  {
    label:
      "Indian Institute of Information Technology, Design and Manufacturing",
    value: 274,
  },
  { label: "Indian Institute of Information Technology, Guwahati", value: 275 },
  { label: "Indian Institute of Information Technology, Kalyani", value: 276 },
  { label: "Indian Institute of Information Technology, Kottayam", value: 277 },
  { label: "Indian Institute of Information Technology, Lucknow", value: 278 },
  { label: "Indian Institute of Information Technology, Manipur", value: 279 },
  { label: "Indian Institute of Information Technology, Pune", value: 280 },
  { label: "Indian Institute of Information Technology, Sri City", value: 281 },
  { label: "Indian Institute of Information Technology, Una", value: 282 },
  { label: "Indian Institute of Information Technology, Vadodara", value: 283 },
  { label: "Indian Institute of Public Health", value: 284 },
  { label: "Indian Institute of Science", value: 285 },
  {
    label: "Indian Institute of Science Education and Research, Bhopal",
    value: 286,
  },
  {
    label: "Indian Institute of Science Education and Research, Kolkata",
    value: 287,
  },
  {
    label: "Indian Institute of Science Education and Research, Mohali",
    value: 288,
  },
  {
    label: "Indian Institute of Science Education and Research, Pune",
    value: 289,
  },
  {
    label:
      "Indian Institute of Science Education and Research, Thiruvananthapuram",
    value: 290,
  },
  { label: "Indian Institute of Space Science and Technology", value: 291 },
  { label: "Indian Institute of Teacher Education", value: 292 },
  { label: "Indian Institute of Technology Bhubaneswar", value: 293 },
  { label: "Indian Institute of Technology Bombay", value: 294 },
  { label: "Indian Institute of Technology Delhi", value: 295 },
  { label: "Indian Institute of Technology Gandhinagar", value: 296 },
  { label: "Indian Institute of Technology Guwahati", value: 297 },
  { label: "Indian Institute of Technology Hyderabad", value: 298 },
  { label: "Indian Institute of Technology Indore", value: 299 },
  { label: "Indian Institute of Technology Jodhpur", value: 300 },
  { label: "Indian Institute of Technology Kanpur", value: 301 },
  { label: "Indian Institute of Technology Madras", value: 303 },
  { label: "Indian Institute of Technology Mandi", value: 304 },
  { label: "Indian Institute of Technology Patna", value: 305 },
  { label: "Indian Institute of Technology Roorkee", value: 306 },
  { label: "Indian Institute of Technology Ropar", value: 307 },
  { label: "Indian Institute of Technology, BHU", value: 308 },
  { label: "Indian Maritime University", value: 309 },
  { label: "Indian School of Mines", value: 310 },
  { label: "Indian Statistical Institute", value: 311 },
  { label: "Indian Veterinary Research Institute", value: 312 },
  { label: "Indira Gandhi Delhi Technical University for Women", value: 313 },
  { label: "Indira Gandhi Institute of Development Research", value: 314 },
  { label: "Indira Gandhi Institute of Medical Sciences", value: 315 },
  { label: "Indira Gandhi Krishi Vishwavidyalaya", value: 316 },
  { label: "Indira Gandhi National Tribal University", value: 317 },
  {
    label: "Indira Gandhi Technological and Medical Sciences University",
    value: 318,
  },
  { label: "Indira Gandhi University, Meerpur", value: 319 },
  { label: "Indira Kala Sangeet Vishwavidyalaya", value: 320 },
  { label: "Indraprastha Institute of Information Technology", value: 321 },
  { label: "Indrashil University", value: 322 },
  { label: "Indus International University", value: 323 },
  { label: "Indus University", value: 324 },
  { label: "Institute of Advanced Research", value: 325 },
  { label: "Institute of Advanced Studies in Education", value: 326 },
  { label: "Institute of Chemical Technology", value: 327 },
  {
    label: "Institute of Infrastructure, Technology, Research and Management",
    value: 328,
  },
  { label: "Integral University", value: 329 },
  { label: "International Institute for Population Sciences", value: 330 },
  {
    label: "International Institute of Information Technology Bangalore",
    value: 331,
  },
  {
    label: "International Institute of Information Technology, Bhubaneswar",
    value: 332,
  },
  {
    label: "International Institute of Information Technology, Hyderabad",
    value: 333,
  },
  {
    label: "International Institute of Information Technology, Naya Raipur",
    value: 334,
  },
  { label: "Invertis University", value: 335 },
  { label: "ISBM University", value: 336 },
  { label: "Islamic University of Science and Technology", value: 337 },
  { label: "ITM University Gwalior", value: 338 },
  { label: "ITM University Raipur", value: 339 },
  { label: "ITM Vocational University", value: 340 },
  { label: "J.C. Bose University of Science and Technology", value: 341 },
  { label: "Jadavpur University", value: 342 },
  {
    label: "Jagadguru Ramanandacharya Rajasthan Sanskrit University",
    value: 343,
  },
  { label: "Jagadguru Rambhadracharya Handicapped University", value: 344 },
  { label: "Jagan Nath University", value: 345 },
  { label: "Jagannath University", value: 346 },
  { label: "Jagran Lakecity University", value: 347 },
  { label: "Jai Narain Vyas University", value: 348 },
  { label: "Jai Prakash Vishwavidyalaya", value: 349 },
  { label: "Jain University", value: 350 },
  { label: "Jain Vishva Bharati Institute", value: 351 },
  { label: "Jaipur National University", value: 352 },
  { label: "Jamia Hamdard", value: 353 },
  { label: "Jamia Millia Islamia", value: 354 },
  { label: "Jananayak Chandrashekhar University", value: 355 },
  { label: "Janardan Rai Nagar Rajasthan Vidhyapeeth University", value: 356 },
  {
    label:
      "Jawaharlal Institute of Postgraduate Medical Education and Research",
    value: 357,
  },
  {
    label: "Jawaharlal Nehru Architecture and Fine Arts University",
    value: 358,
  },
  {
    label: "Jawaharlal Nehru Centre for Advanced Scientific Research",
    value: 359,
  },
  { label: "Jawaharlal Nehru Krishi Vishwavidyalaya", value: 360 },
  { label: "Jawaharlal Nehru Technological University, Hyderabad", value: 361 },
  { label: "Jawaharlal Nehru Technological University, Anantapur", value: 362 },
  { label: "Jawaharlal Nehru Technological University, Kakinada", value: 363 },
  { label: "Jawaharlal Nehru University", value: 364 },
  { label: "Jayoti Vidyapeeth Women's University", value: 365 },
  { label: "Jaypee Institute of Information Technology", value: 366 },
  { label: "Jaypee University Anoopshahr", value: 367 },
  { label: "Jaypee University of Engineering and Technology", value: 368 },
  { label: "Jaypee University of Information Technology", value: 369 },
  { label: "JECRC University", value: 370 },
  { label: "Jharkhand Rai University", value: 371 },
  { label: "Jharkhand Raksha Shakti University", value: 372 },
  { label: "JIS University", value: 373 },
  { label: "Jiwaji University", value: 374 },
  { label: "JK Lakshmipat University", value: 375 },
  { label: "Jodhpur National University", value: 376 },
  { label: "JS University", value: 377 },
  { label: "JSS Academy of Higher Education and Research", value: 378 },
  { label: "JSS Science and Technology University", value: 379 },
  { label: "Junagadh Agricultural University", value: 380 },
  { label: "K L University", value: 381 },
  { label: "K.K. University", value: 382 },
  { label: "K.R. Mangalam University", value: 383 },
  { label: "Kadi Sarva Vishwavidyalaya", value: 384 },
  { label: "Kakatiya University", value: 385 },
  { label: "Kalasalingam Academy of Research and Education", value: 386 },
  { label: "Kalinga University", value: 387 },
  { label: "Kamdhenu University", value: 388 },
  { label: "Kameshwar Singh Darbhanga Sanskrit University", value: 389 },
  { label: "Kannada University", value: 390 },
  { label: "Kannur University", value: 391 },
  { label: "Karnatak University", value: 392 },
  { label: "Karnataka Janapada Vishwavidyalaya", value: 393 },
  { label: "Karnataka Samskrit University", value: 394 },
  { label: "Karnataka State Law University", value: 395 },
  {
    label: "Karnataka State Rural Development and Panchayat Raj University",
    value: 396,
  },
  { label: "Karnataka State Women's University", value: 397 },
  {
    label: "Karnataka Veterinary, Animal and Fisheries Sciences University",
    value: 398,
  },
  { label: "Karnavati University", value: 399 },
  { label: "Karpagam Academy of Higher Education", value: 400 },
  { label: "Karunya Institute of Technology and Sciences", value: 401 },
  {
    label: "Kavayitri Bahinabai Chaudhari North Maharashtra University",
    value: 402,
  },
  { label: "Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya", value: 403 },
  { label: "Kazi Nazrul University", value: 404 },
  { label: "Kaziranga University", value: 405 },
  { label: "Kerala Agricultural University", value: 406 },
  { label: "Kerala Kalamandalam", value: 407 },
  { label: "Kerala University of Fisheries and Ocean Studies", value: 408 },
  { label: "Kerala University of Health Sciences", value: 409 },
  { label: "Kerala Veterinary and Animal Sciences University", value: 410 },
  { label: "Khallikote University Berhampur", value: 411 },
  { label: "Khwaja Moinuddin Chishti Language University", value: 412 },
  { label: "KIIT University", value: 413 },
  { label: "King George's Medical University", value: 414 },
  { label: "KLE Technological University", value: 415 },
  { label: "KLE University", value: 416 },
  { label: "Kolhan University", value: 417 },
  { label: "Krantiguru Shyamji Krishna Verma Kachchh University", value: 418 },
  { label: "Krishna Institute of Medical Sciences", value: 419 },
  { label: "Krishna University", value: 420 },
  { label: "KSGH Music and Performing Arts University", value: 421 },
  {
    label: "Kumar Bhaskar Varma Sanskrit and Ancient Studies University",
    value: 422,
  },
  { label: "Kumaun University", value: 423 },
  { label: "Kurukshetra University", value: 424 },
  {
    label: "Kushabhau Thakre Patrakarita Avam Jansanchar University",
    value: 425,
  },
  { label: "Kuvempu University", value: 426 },
  { label: "Lakshmibai National Institute of Physical Education", value: 427 },
  { label: "Lakulish Yoga University", value: 428 },
  {
    label: "Lala Lajpat Rai University of Veterinary and Animal Sciences",
    value: 429,
  },
  { label: "Lalit Narayan Mithila University", value: 430 },
  { label: "Lingaya's University", value: 431 },
  { label: "LNCT University", value: 432 },
  { label: "Lovely Professional University", value: 433 },
  { label: "M.J.P. Rohilkhand University", value: 434 },
  { label: "Madan Mohan Malaviya University of Technology", value: 435 },
  { label: "Madhav University", value: 436 },
  { label: "Madhyanchal Professional University", value: 437 },
  { label: "Madurai Kamaraj University", value: 438 },
  { label: "Magadh University", value: 439 },
  { label: "Mahapurusha Srimanta Sankaradeva Viswavidyalaya", value: 440 },
  { label: "Maharaja Agrasen University", value: 441 },
  { label: "Maharaja Bir Bikram University", value: 442 },
  { label: "Maharaja Chhatrasal Bundelkhand University", value: 443 },
  { label: "Maharaja Ganga Singh University", value: 444 },
  { label: "Maharaja Krishnakumarsinhji Bhavnagar University", value: 445 },
  { label: "Maharaja Ranjit Singh Punjab Technical University", value: 446 },
  { label: "Maharaja Surajmal Brij University", value: 447 },
  {
    label: "Maharana Pratap University of Agriculture and Technology, Udaipur",
    value: 448,
  },
  { label: "Maharashtra Animal and Fishery Sciences University", value: 449 },
  { label: "Maharashtra National Law University Mumbai", value: 450 },
  { label: "Maharashtra National Law University, Aurangabad", value: 451 },
  { label: "Maharashtra National Law University, Nagpur", value: 452 },
  { label: "Maharashtra University of Health Sciences", value: 453 },
  { label: "Maharishi Arvind University, Jaipur", value: 454 },
  { label: "Maharishi Dayanand University", value: 455 },
  { label: "Maharishi Mahesh Yogi Vedic Vishwavidyalaya", value: 456 },
  { label: "Maharishi Markandeshwar University, Mullana", value: 457 },
  { label: "Maharishi Markandeshwar University, Sadopur", value: 458 },
  { label: "Maharishi Markandeshwar University, Solan", value: 459 },
  { label: "Maharishi University", value: 460 },
  { label: "Maharishi University of Management and Technology", value: 461 },
  { label: "Maharshi Dayanand Saraswati University", value: 462 },
  { label: "Maharshi Panini Sanskrit Vishwavidyalaya", value: 463 },
  { label: "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya", value: 464 },
  { label: "Mahatma Gandhi Central University, Motihari", value: 465 },
  { label: "Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya", value: 466 },
  { label: "Mahatma Gandhi Kashi Vidyapeeth", value: 467 },
  { label: "Mahatma Gandhi University", value: 468 },
  {
    label: "Mahatma Gandhi University of Medical Sciences and Technology",
    value: 469,
  },
  { label: "Mahatma Gandhi University, Meghalaya", value: 470 },
  { label: "Mahatma Gandhi University, Nalgonda", value: 471 },
  { label: "Mahatma Jyoti Rao Phoole University", value: 472 },
  { label: "Mahatma Phule Krishi Vidyapeeth", value: 473 },
  {
    label: "Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya",
    value: 474,
  },
  { label: "Malaviya National Institute of Technology, Jaipur", value: 475 },
  { label: "Malwanchal University", value: 476 },
  { label: "Manav Bharti University", value: 477 },
  {
    label: "Manav Rachna International Institute of Research and Studies",
    value: 478,
  },
  { label: "Manav Rachna University", value: 479 },
  { label: "Mandsaur University", value: 480 },
  { label: "Mangalayatan University", value: 481 },
  { label: "Mangalore University", value: 482 },
  { label: "Manipal Academy of Higher Education", value: 483 },
  { label: "Manipur International University", value: 484 },
  { label: "Manipur Technical University", value: 485 },
  { label: "Manipur University", value: 486 },
  { label: "Manipur University of Culture", value: 487 },
  { label: "Manonmaniam Sundaranar University", value: 488 },
  { label: "Martin Luther Christian University", value: 489 },
  { label: "Marwadi University", value: 490 },
  { label: "MATS University", value: 491 },
  {
    label: "Maulana Abul Kalam Azad University of Technology, West Bengal",
    value: 492,
  },
  { label: "Maulana Azad National Institute of Technology", value: 493 },
  { label: "Maulana Azad National Urdu University", value: 494 },
  { label: "Maulana Azad University, Jodhpur", value: 495 },
  { label: "Maulana Mazharul Haque Arabic and Persian University", value: 496 },
  { label: "Medi-Caps University", value: 497 },
  { label: "Meenakshi Academy of Higher Education and Research", value: 498 },
  { label: "Mewar University", value: 499 },
  { label: "MGM Institute of Health Sciences", value: 500 },
  { label: "MIT Art Design and Technology University", value: 501 },
  { label: "MIT University", value: 502 },
  { label: "Mizoram University", value: 503 },
  { label: "Mody University of Science and Technology", value: 504 },
  { label: "Mohammad Ali Jauhar University", value: 505 },
  { label: "Mohanlal Sukhadia University", value: 506 },
  { label: "Monad University", value: 507 },
  { label: "Mother Teresa Women's University", value: 508 },
  { label: "Motherhood University", value: 509 },
  {
    label: "Motilal Nehru National Institute of Technology Allahabad",
    value: 510,
  },
  { label: "Murshidabad University", value: 511 },
  { label: "MVN University", value: 512 },
  { label: "Nagaland University", value: 513 },
  { label: "Nalanda University", value: 514 },
  { label: "NALSAR University of Law", value: 515 },
  { label: "Nanaji Deshmukh Veterinary Science University", value: 516 },
  {
    label: "Narendra Dev University of Agriculture and Technology",
    value: 517,
  },
  {
    label: "Narsee Monjee Institute of Management and Higher Studies",
    value: 518,
  },
  { label: "National Dairy Research Institute", value: 519 },
  { label: "National Institute of Design", value: 520 },
  {
    label: "National Institute of Educational Planning and Administration",
    value: 521,
  },
  { label: "National Institute of Fashion Technology", value: 522 },
  {
    label:
      "National Institute of Food Technology Entrepreneurship and Management",
    value: 523,
  },
  {
    label: "National Institute of Mental Health and Neuro Sciences",
    value: 524,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Ahmedabad",
    value: 525,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Guwahati",
    value: 526,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Hajipur",
    value: 527,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Hyderabad",
    value: 528,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Kolkata",
    value: 529,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, Rae Bareli",
    value: 530,
  },
  {
    label:
      "National Institute of Pharmaceutical Education and Research, S.A.S. Nagar",
    value: 531,
  },
  { label: "National Institute of Technology, Agartala", value: 532 },
  { label: "National Institute of Technology, Arunachal Pradesh", value: 533 },
  { label: "National Institute of Technology, Calicut", value: 534 },
  { label: "National Institute of Technology, Delhi", value: 535 },
  { label: "National Institute of Technology, Durgapur", value: 536 },
  { label: "National Institute of Technology, Goa", value: 537 },
  { label: "National Institute of Technology, Hamirpur", value: 538 },
  { label: "National Institute of Technology, Jamshedpur", value: 539 },
  { label: "National Institute of Technology, Karnataka", value: 540 },
  { label: "National Institute of Technology, Kurukshetra", value: 541 },
  { label: "National Institute of Technology, Manipur", value: 542 },
  { label: "National Institute of Technology, Meghalaya", value: 543 },
  { label: "National Institute of Technology, Mizoram", value: 544 },
  { label: "National Institute of Technology, Nagaland", value: 545 },
  { label: "National Institute of Technology, Patna", value: 546 },
  { label: "National Institute of Technology, Puducherry", value: 547 },
  { label: "National Institute of Technology, Raipur", value: 548 },
  { label: "National Institute of Technology, Rourkela", value: 549 },
  { label: "National Institute of Technology, Sikkim", value: 550 },
  { label: "National Institute of Technology, Silchar", value: 551 },
  { label: "National Institute of Technology, Srinagar", value: 552 },
  { label: "National Institute of Technology, Tiruchirappalli", value: 553 },
  { label: "National Institute of Technology, Uttarakhand", value: 554 },
  { label: "National Institute of Technology, Warangal", value: 555 },
  { label: "National Law Institute University", value: 556 },
  { label: "National Law School of India University", value: 557 },
  { label: "National Law University and Judicial Academy", value: 558 },
  { label: "National Law University Odisha", value: 559 },
  { label: "National Law University, Delhi", value: 560 },
  { label: "National Law University, Jodhpur", value: 561 },
  { label: "National Sports University", value: 562 },
  { label: "National University of Study and Research in Law", value: 563 },
  { label: "Nava Nalanda Mahavihara", value: 564 },
  { label: "Navrachana University", value: 565 },
  { label: "Navsari Agricultural University", value: 566 },
  { label: "Nehru Gram Bharati Vishwavidyalaya", value: 567 },
  { label: "NIILM University", value: 568 },
  { label: "NIIT University", value: 569 },
  { label: "Nilamber-Pitamber University", value: 570 },
  { label: "NIMS University", value: 571 },
  { label: "Nirma University", value: 572 },
  { label: "NITTE University", value: 573 },
  { label: "Nizam's Institute of Medical Sciences", value: 574 },
  { label: "Noida International University", value: 575 },
  { label: "North East Frontier Technical University", value: 576 },
  { label: "North Eastern Hill University", value: 577 },
  {
    label: "North Eastern Regional Institute of Science and Technology",
    value: 578,
  },
  { label: "North Orissa University", value: 579 },
  { label: "O.P. Jindal Global University", value: 580 },
  { label: "O.P. Jindal University", value: 581 },
  { label: "Odisha University of Agriculture and Technology", value: 582 },
  { label: "OPJS University", value: 583 },
  { label: "Oriental University", value: 584 },
  { label: "Osmania University", value: 585 },
  { label: "P P Savani University", value: 586 },
  { label: "P.K. University", value: 587 },
  { label: "Pacific Medical University", value: 588 },
  { label: "Pacific University, India", value: 589 },
  { label: "Padmashree Dr. D.Y. Patil Vidyapith", value: 590 },
  { label: "Palamuru University", value: 591 },
  { label: "Pandit Deendayal Petroleum University", value: 592 },
  { label: "Pandit Deendayal Upadhyaya Shekhawati University", value: 593 },
  { label: "Pandit Ravishankar Shukla University", value: 594 },
  { label: "Panjab University", value: 595 },
  { label: "Parul University", value: 596 },
  { label: "Patna University", value: 597 },
  { label: "PDM University", value: 598 },
  {
    label:
      "PDPM Indian Institute of Information Technology, Design and Manufacturing",
    value: 599,
  },
  { label: "PEC University of Technology", value: 600 },
  { label: "People's University", value: 601 },
  {
    label: "Periyar Maniammai Institute of Science and Technology",
    value: 602,
  },
  { label: "Periyar University", value: 603 },
  { label: "PES University", value: 604 },
  { label: "Plastindia International University", value: 605 },
  { label: "Pondicherry University", value: 606 },
  {
    label: "Ponnaiyan Ramajayam Institute of Science and Technology",
    value: 607,
  },
  { label: "Poornima University", value: 608 },
  {
    label: "Post Graduate Institute of Medical Education and Research",
    value: 609,
  },
  { label: "Potti Sreeramulu Telugu University", value: 610 },
  { label: "Pragyan International University", value: 611 },
  { label: "Pratap University", value: 612 },
  { label: "Pravara Institute of Medical Sciences", value: 613 },
  { label: "Presidency University", value: 614 },
  { label: "Presidency University", value: 615 },
  { label: "Prof. Rajendra Singh (Rajju Bhaiya) University", value: 616 },
  {
    label: "Professor Jayashankar Telangana State Agricultural University",
    value: 617,
  },
  {
    label: "Pt. Bhagwat Dayal Sharma University of Health Sciences",
    value: 618,
  },
  { label: "Punjab Agricultural University", value: 619 },
  { label: "Punjab Technical University", value: 620 },
  { label: "Punjabi University Patiala", value: 621 },
  { label: "Punyashlok Ahilyadevi Holkar University, Solapur", value: 622 },
  { label: "Quantum University", value: 623 },
  { label: "Rabindra Bharati University", value: 624 },
  { label: "Rabindranath Tagore University", value: 625 },
  { label: "Raffles University", value: 626 },
  { label: "Rai Technology University", value: 627 },
  { label: "Rai University", value: 628 },
  { label: "Raiganj University", value: 629 },
  { label: "Raj Rishi Bharthari Matsya University", value: 630 },
  { label: "Raja Mansingh Tomar Music and Arts University", value: 631 },
  { label: "Rajasthan Technical University Kota", value: 632 },
  { label: "Rajasthan University of Health Sciences", value: 633 },
  {
    label: "Rajasthan University of Veterinary and Animal Sciences",
    value: 634,
  },
  { label: "Rajiv Gandhi Institute of Petroleum Technology", value: 635 },
  { label: "Rajiv Gandhi National Aviation University", value: 636 },
  { label: "Rajiv Gandhi National Institute of Youth Development", value: 637 },
  { label: "Rajiv Gandhi National University of Law", value: 638 },
  { label: "Rajiv Gandhi Proudyogiki Vishwavidyalaya", value: 639 },
  { label: "Rajiv Gandhi University", value: 640 },
  { label: "Rajiv Gandhi University of Health Sciences", value: 641 },
  { label: "Rajiv Gandhi University of Knowledge Technologies", value: 642 },
  { label: "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya", value: 643 },
  { label: "Rama Devi Women's University", value: 644 },
  { label: "Rama University", value: 645 },
  { label: "Ramaiah University of Applied Sciences", value: 646 },
  {
    label: "Ramakrishna Mission Vivekananda Educational and Research Institute",
    value: 647,
  },
  { label: "Ranchi University", value: 648 },
  { label: "Rani Channamma University, Belagavi", value: 649 },
  { label: "Rani Durgavati Vishwavidyalaya", value: 650 },
  { label: "Rani Lakshmi Bai Central Agricultural University", value: 651 },
  { label: "Ras Bihari Bose Subharti University", value: 652 },
  { label: "Rashtrasant Tukadoji Maharaj Nagpur University", value: 653 },
  { label: "Rashtriya Raksha University", value: 654 },
  { label: "Rashtriya Sanskrit Sansthan University", value: 655 },
  { label: "Rashtriya Sanskrit Vidyapeetha", value: 656 },
  { label: "Ravenshaw University", value: 657 },
  { label: "Rayalaseema University", value: 658 },
  { label: "Rayat-Bahra University", value: 659 },
  { label: "REVA University", value: 660 },
  { label: "RIMT University", value: 661 },
  { label: "Rishihood University", value: 662 },
  { label: "RK University", value: 663 },
  { label: "RKDF University", value: 664 },
  { label: "Sabarmati University", value: 665 },
  { label: "Sage University", value: 666 },
  { label: "Sai Nath University, Ranchi", value: 667 },
  { label: "Sai Tirupati University", value: 668 },
  {
    label: "Sam Higginbottom Institute of Agriculture, Technology and Sciences",
    value: 669,
  },
  { label: "Sambalpur University", value: 670 },
  { label: "Sampurnanand Sanskrit Vishvavidyalaya", value: 671 },
  { label: "Sanchi University of Buddhist-Indic Studies", value: 672 },
  { label: "Sandip University", value: 673 },
  { label: "Sandip University, Sijoul", value: 674 },
  { label: "Sangai International University", value: 675 },
  { label: "Sangam University", value: 676 },
  {
    label: "Sanjay Gandhi Post Graduate Institute of Medical Sciences",
    value: 677,
  },
  { label: "Sanjay Ghodawat University", value: 678 },
  { label: "Sankalchand Patel University", value: 679 },
  { label: "Sanskriti University", value: 680 },
  { label: "Sant Baba Bhag Singh University", value: 681 },
  { label: "Sant Gadge Baba Amravati University", value: 682 },
  {
    label: "Sant Longowal Institute of Engineering and Technology",
    value: 683,
  },
  { label: "Santosh University", value: 684 },
  { label: "Sarala Birla University", value: 685 },
  { label: "Sardar Patel University", value: 686 },
  {
    label: "Sardar Patel University of Police, Security and Criminal Justice",
    value: 687,
  },
  {
    label: "Sardar Vallabhbhai National Institute of Technology, Surat",
    value: 688,
  },
  {
    label: "Sardar Vallabhbhai Patel University of Agriculture and Technology",
    value: 689,
  },
  { label: "Sardarkrushinagar Dantiwada Agricultural University", value: 690 },
  { label: "Sarguja University", value: 691 },
  { label: "Sarvepalli Radhakrishnan University", value: 692 },
  { label: "SASTRA University", value: 693 },
  { label: "Satavahana University", value: 694 },
  { label: "Sathyabama Institute of Science and Technology", value: 695 },
  { label: "Saurashtra University", value: 696 },
  { label: "Saveetha Institute of Medical and Technical Sciences", value: 697 },
  { label: "Savitribai Phule Pune University", value: 698 },
  { label: "School of Planning and Architecture, Bhopal", value: 699 },
  { label: "School of Planning and Architecture, Delhi", value: 700 },
  { label: "School of Planning and Architecture, Vijayawada", value: 701 },
  { label: "Seacom Skills University", value: 702 },
  { label: "Sharda University", value: 703 },
  { label: "Sharnbasva University", value: 704 },
  {
    label:
      "Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu",
    value: 705,
  },
  {
    label:
      "Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir",
    value: 706,
  },
  { label: "Sher-i-Kashmir Institute of Medical Sciences", value: 707 },
  { label: "Shiv Nadar University", value: 708 },
  { label: "Shivaji University", value: 709 },
  { label: "Shobhit Institute of Engineering and Technology", value: 710 },
  {
    label: "Shoolini University of Biotechnology and Management Sciences",
    value: 711,
  },
  { label: "Shree Guru Gobind Singh Tricentenary University", value: 712 },
  { label: "Shree Somnath Sanskrit University", value: 713 },
  {
    label: "Shreemati Nathibai Damodar Thackersey Women's University",
    value: 714,
  },
  { label: "Shri Govind Guru University", value: 715 },
  { label: "Shri Guru Ram Rai Education Mission", value: 716 },
  { label: "Shri Guru Ram Rai University", value: 717 },
  { label: "Shri Jagannath Sanskrit Vishvavidyalaya", value: 718 },
  { label: "Shri Jagdishprasad Jhabrmal Tibrewala University", value: 719 },
  {
    label: "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha",
    value: 720,
  },
  { label: "Shri Mata Vaishno Devi University", value: 721 },
  { label: "Shri Ramswaroop Memorial University", value: 722 },
  { label: "Shri Vaishnav Vidyapeeth Vishwavidyalaya", value: 723 },
  { label: "Shri Venkateshwara University", value: 724 },
  { label: "Shri Vishwakarma Skill University", value: 725 },
  { label: "Shridhar University", value: 726 },
  { label: "Siddharth University", value: 727 },
  { label: "Sidho Kanho Birsha University", value: 728 },
  { label: "Sido Kanhu Murmu University", value: 729 },
  { label: "Sikkim Manipal University", value: 730 },
  { label: "Sikkim University", value: 731 },
  { label: "Siksha 'O' Anusandhan", value: 732 },
  { label: "Singhania University", value: 733 },
  { label: "Sir Padampat Singhania University", value: 734 },
  { label: "South Asian University", value: 735 },
  { label: "Spicer Adventist University", value: 736 },
  {
    label: "Sree Chitra Thirunal Institute of Medical Sciences and Technology",
    value: 737,
  },
  { label: "Sree Sankaracharya University of Sanskrit", value: 738 },
  { label: "Sri Balaji Vidyapeeth", value: 739 },
  {
    label: "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya",
    value: 740,
  },
  { label: "Sri Dev Suman Uttarakhand University", value: 741 },
  {
    label: "Sri Devaraj Urs Academy of Higher Education and Research",
    value: 742,
  },
  { label: "Sri Guru Granth Sahib World University", value: 743 },
  { label: "Sri Guru Ram Das University of Health Sciences", value: 744 },
  {
    label: "Sri Konda Laxman Telangana State Horticultural University",
    value: 745,
  },
  { label: "Sri Krishnadevaraya University", value: 746 },
  { label: "Sri Padmavati Mahila Visvavidyalayam", value: 747 },
  {
    label: "Sri Ramachandra Institute of Higher Education and Research",
    value: 748,
  },
  { label: "Sri Sai University", value: 749 },
  { label: "Sri Sathya Sai Institute of Higher Learning", value: 750 },
  {
    label: "Sri Satya Sai University of Technology and Medical Sciences",
    value: 751,
  },
  { label: "Sri Siddhartha Academy of Higher Education", value: 752 },
  { label: "Sri Sri University", value: 753 },
  { label: "Sri Venkateswara Institute of Medical Sciences", value: 754 },
  { label: "Sri Venkateswara University", value: 755 },
  { label: "Sri Venkateswara Vedic University", value: 756 },
  { label: "Sri Venkateswara Veterinary University", value: 757 },
  { label: "Srimanta Sankaradeva University of Health Sciences", value: 758 },
  { label: "Srinivas University", value: 759 },
  { label: "SRM Institute of Science and Technology", value: 760 },
  { label: "SRM University Haryana", value: 761 },
  { label: "SRM University, Sikkim", value: 762 },
  { label: "St. Joseph University", value: 763 },
  {
    label: "St. Peter's Institute of Higher Education and Research",
    value: 764,
  },
  { label: "St. Xavier's University", value: 765 },
  { label: "Starex University", value: 766 },
  { label: "State University of Performing and Visual Arts", value: 767 },
  { label: "Suamandeep Vidyapeeth", value: 768 },
  { label: "Sunrise University", value: 769 },
  { label: "Suresh Gyan Vihar University", value: 770 },
  { label: "Sushant University", value: 771 },
  { label: "Swami Keshwanand Rajasthan Agricultural University", value: 772 },
  { label: "Swami Rama Himalayan University", value: 773 },
  { label: "Swami Ramanand Teerth Marathwada University", value: 774 },
  { label: "Swami Vivekanand Subharti University", value: 775 },
  { label: "Swami Vivekanand University", value: 776 },
  { label: "Swami Vivekananda Yoga Anusandhana Samsthana", value: 777 },
  { label: "Swarnim Gujarat Sports University", value: 778 },
  { label: "Swarnim Startup and Innovation University", value: 779 },
  { label: "Symbiosis International University", value: 780 },
  { label: "Symbiosis University of Applied Sciences", value: 781 },
  { label: "Tamil Nadu Agricultural University", value: 782 },
  { label: "Tamil Nadu Dr Ambedkar Law University", value: 783 },
  { label: "Tamil Nadu Dr. J. Jayalalithaa Fisheries University", value: 784 },
  { label: "Tamil Nadu Dr. M.G.R.Medical University", value: 785 },
  {
    label: "Tamil Nadu Dr.J Jayalalithaa Music and Fine Arts University",
    value: 786,
  },
  { label: "Tamil Nadu National Law University", value: 787 },
  { label: "Tamil Nadu Physical Education and Sports University", value: 788 },
  { label: "Tamil Nadu Teacher Education University", value: 789 },
  { label: "Tamil Nadu Veterinary and Animal Sciences University", value: 790 },
  { label: "Tamil University", value: 791 },
  { label: "Tantia University", value: 792 },
  { label: "Tata Institute of Fundamental Research", value: 793 },
  { label: "Tata Institute of Social Sciences", value: 794 },
  { label: "TeamLease Skills University", value: 795 },
  { label: "Techno India University", value: 796 },
  { label: "Teerthanker Mahaveer University", value: 797 },
  { label: "Telangana University", value: 798 },
  { label: "TERI School of Advanced Studies", value: 799 },
  { label: "Tezpur University", value: 800 },
  { label: "Thapar Institute of Engineering and Technology", value: 801 },
  { label: "The English and Foreign Languages University", value: 802 },
  { label: "The IIS University", value: 803 },
  { label: "The Indian Law Institute", value: 804 },
  { label: "The LNM Institute of Information Technology", value: 805 },
  { label: "The Maharaja Sayajirao University of Baroda", value: 806 },
  { label: "The National University of Advanced Legal Studies", value: 807 },
  { label: "The Neotia University", value: 808 },
  { label: "The Northcap University", value: 809 },
  { label: "The Sanskrit College and University", value: 810 },
  {
    label: "The West Bengal National University of Juridical Sciences",
    value: 811,
  },
  { label: "Thiruvalluvar University", value: 812 },
  { label: "Thunchath Ezhuthachan Malayalam University", value: 813 },
  { label: "Tilak Maharashtra Vidyapeeth", value: 814 },
  { label: "Tilka Manjhi Bhagalpur University", value: 815 },
  { label: "Tripura University", value: 816 },
  { label: "Tumkur University", value: 817 },
  {
    label:
      "U.P. Pt. Deen Dayal Upadhyaya Veterinary Science University and Cattle Research Institute",
    value: 818,
  },
  { label: "Uka Tarsadia University", value: 819 },
  {
    label: "University of Agricultural and Horticultural Sciences, Shivamogga",
    value: 820,
  },
  { label: "University of Agricultural Sciences, Bangalore", value: 821 },
  { label: "University of Agricultural Sciences, Dharwad", value: 822 },
  { label: "University of Agricultural Sciences, Raichur", value: 823 },
  { label: "University of Allahabad", value: 824 },
  { label: "University of Burdwan", value: 825 },
  { label: "University of Calcutta", value: 826 },
  { label: "University of Calicut", value: 827 },
  { label: "University of Delhi", value: 828 },
  { label: "University of Engineering and Management, Kolkata", value: 829 },
  { label: "University of Gour Banga", value: 830 },
  { label: "University of Horticultural Sciences, Bagalkot", value: 831 },
  { label: "University of Hyderabad", value: 832 },
  { label: "University of Jammu", value: 833 },
  { label: "University of Kalyani", value: 834 },
  { label: "University of Kashmir", value: 835 },
  { label: "University of Kerala", value: 836 },
  { label: "University of Kota", value: 837 },
  { label: "University of Lucknow", value: 838 },
  { label: "University of Madras", value: 839 },
  { label: "University of Mumbai", value: 840 },
  { label: "University of Mysore", value: 841 },
  { label: "University of North Bengal", value: 842 },
  { label: "University of Patanjali", value: 843 },
  { label: "University of Petroleum and Energy Studies", value: 844 },
  { label: "University of Rajasthan", value: 845 },
  { label: "University of Science and Technology, Meghalaya", value: 846 },
  { label: "University of Technology", value: 847 },
  {
    label: "University of Trans-Disciplinary Health Sciences and Technology",
    value: 848,
  },
  { label: "Usha Martin University", value: 849 },
  { label: "Utkal University", value: 850 },
  { label: "Utkal University of Culture", value: 851 },
  { label: "Uttar Banga Krishi Viswavidyalaya", value: 852 },
  { label: "Uttar Pradesh University of Medical Sciences", value: 853 },
  { label: "Uttarakhand Aawasiya Vishwavidyalaya, Almora", value: 854 },
  { label: "Uttarakhand Ayurved University", value: 855 },
  { label: "Uttarakhand Sanskrit University", value: 856 },
  { label: "Uttarakhand Technical University", value: 857 },
  { label: "Uttaranchal University", value: 858 },
  { label: "Vasantrao Naik Marathwada Krishi Vidyapeeth", value: 859 },
  { label: "Veer Bahadur Singh Purvanchal University", value: 860 },
  {
    label:
      "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry",
    value: 861,
  },
  { label: "Veer Kunwar Singh University", value: 862 },
  { label: "Veer Narmad South Gujarat University", value: 863 },
  { label: "Veer Surendra Sai University of Technology", value: 864 },
  {
    label:
      "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
    value: 865,
  },
  { label: "Vellore Institute of Technology", value: 866 },
  { label: "Vels University", value: 867 },
  { label: "Vidyasagar University", value: 868 },
  { label: "Vignan University", value: 869 },
  { label: "Vijayanagara Sri Krishnadevaraya University", value: 870 },
  { label: "Vikram University", value: 871 },
  { label: "Vikrama Simhapuri University", value: 872 },
  { label: "Vinayaka Mission's Research Foundation", value: 873 },
  { label: "Vinayaka Missions Sikkim University", value: 874 },
  { label: "Vinoba Bhave University", value: 875 },
  { label: "Vishwakarma University", value: 876 },
  { label: "Visva-Bharati University", value: 877 },
  { label: "Visvesvaraya National Institute of Technology", value: 878 },
  { label: "Visvesvaraya Technological University", value: 879 },
  { label: "VIT Bhopal University", value: 880 },
  { label: "Vivekananda Global University", value: 881 },
  { label: "West Bengal State University", value: 882 },
  {
    label: "West Bengal University of Animal and Fishery Sciences",
    value: 883,
  },
  { label: "West Bengal University of Health Sciences", value: 884 },
  {
    label:
      "West Bengal University of Teachers' Training, Education Planning and Administration",
    value: 885,
  },
  { label: "William Carey University, Meghalaya", value: 886 },
  { label: "XIM University", value: 887 },
  { label: "YBN University", value: 888 },
  { label: "Yenepoya University", value: 889 },
  { label: "Yogi Vemana University", value: 890 },
  { label: "Indian Institute of Technology, Dhanbad", value: 891 },
  { label: "Asansol Polytechnic", value: 892 },
  { label: "Government College of Engineering (GCE) Keonjhar", value: 893 },
  { label: "National Institute of Technology, Suratkal", value: 894 },
  { label: "BIT Sindri", value: 895 },
  { label: "NIT Suratkal", value: 896 },
  { label: "AKS University Satna", value: 897 },
  { label: "Malla Ready Engineering College", value: 898 },
  { label: "College of Engineering, Guindy", value: 899 },
  { label: "Aditya Engineering College, AP", value: 900 },
  { label: "BPUT, Odisha", value: 901 },
  { label: "Bhagwant University, Ajmer", value: 902 },
  { label: "Amity University Jharkhand", value: 903 },
  { label: "Sir Padampat Singhania University Udaipur", value: 904 },
  { label: "Andhra University College of Engineering AP", value: 905 },
  { label: "College of Technology & Engineering, Udaipur", value: 906 },
  { label: "ICFAI University, Jharkhand", value: 907 },
  { label: "Academy of Maritime Education and Training Chenna", value: 908 },
  { label: "Mewar University, Rajsthan", value: 909 },
  { label: "CMJ University, Meghalya", value: 910 },
  { label: "Dr T Thimmaiah Institute of Technology, karnatka", value: 911 },
  { label: "Pacific University, Udaipur", value: 912 },
  {
    label: "Rungta College Of Engineering and Technology, Chhatishgrah",
    value: 913,
  },
  { label: "SHRIDHAR UNIVERSITY, Pilani", value: 914 },
  { label: "Lakshmi Narain College of Technology, Jabalpur, MP", value: 915 },
  { label: "K. K. University, Biharsharif", value: 916 },
  { label: "Shri Rawatpura Sarkar University, Chattisgarh", value: 917 },
  { label: "University of Technology, Jaipur", value: 918 },
  { label: "Kalinga University, Chattisgarh", value: 919 },
  { label: "Acharya Institute of Technology, karnataka", value: 920 },
  { label: "Raj Engineering College, Jodhpur", value: 921 },
  {
    label: "Indian Institute of Petroleum and Energy, Visakhapatnam",
    value: 922,
  },
  { label: "GEC Bilaspur, Chhattisgarh", value: 923 },
  {
    label: "GH RAISONI INSTITUTE OF ENGINEERING AND TECHNOLOGY NAGPUR",
    value: 924,
  },
  { label: " JHARKHAND RAI UNIVERSITY", value: 925 },
  { label: "SAI NATH UNIVERSITY", value: 926 },
  { label: "ICFAI UNIVRSITY", value: 927 },
  { label: "University Institute of Technology R.G.P.V Shahdol", value: 928 },

];

export default collegeData;
